### ISSUE TITLE
application errors

### ISSUE THREAD

**Issue by zetekla** [fede-rodes/meteor-apollo-starter-kit#60]
While processing files with static-html (for target web.browser):
   localhost_2017-12-29_16-09-47.report.html:6: Can't set DOCTYPE here.  (Meteor sets
   <!DOCTYPE html> for you)

**Comment by fede-rodes** [comment]
Hey @zetekla thanks for the feedback.

Unfortunately I cannot reproduce the error. Let's try as follows

Have you followed the steps bellow?
1. clone the repo,
2. install dependencies: `meteor npm install`
3. define settings-dev.json file based on settings-dev.sample.json (you'll need to get some credentials from mailgun and facebook, but you can use settings-dev.sample.json until the error you reported is solved)
4. run: `meteor --settings settings-dev.json`

Questions:
1. this error happening on you local computer or when trying to deploy the app to production (Heroku for instance)?
2. are you on Windows?
3. Could you please copy all the steps you follow until getting the error? :)
4. Try removing node_modules and package-lock.json and re-install the npm dependecies

**Comment by fede-rodes** [comment]
Hey @zetekla any progress on this issue? Where you able to get the boilerplate working?

Cheers

**Comment by fede-rodes** [comment]
Ok, I was able to reproduce the issue by mistake:

```
fede@fede-ThinkPad-T440:~/apollo/meteor-starter-kit$ meteor --settings settings-dev.json
[[[[[ ~/apollo/meteor-starter-kit ]]]]]       

=> Started proxy.                             
=> Errors prevented startup:                  
   
   While processing files with static-html (for target web.browser):
   meteor-apollo-starter-dev.herokuapp.com_2018-01-14_15-05-37.report.html:6:
   Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
   
=> Your application has errors. Waiting for file change.
=> Started MongoDB.
```

This happened after running lighthouse audit on my /meteor-starter-kit app folder. As a result the file mentioned above (meteor-apollo-starter-dev.herokuapp.com_2018-01-14_15-05-37.report.html) was saved in my app root folder which caused the error.

So, in order to solve this problem, you can either run lighthouse outside your /meteor-starter-kit app's folder or, in case you do run the audit in your app's folder, just remember to remove the report generated by the audit.
